// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCORQn3b4HRiBLSgRMrbIgGMq4saEG8Nso',
    appId: '1:279667373401:web:7f9f970d2e98ecaffbc848',
    messagingSenderId: '279667373401',
    projectId: 'pokedex-3fc17',
    authDomain: 'pokedex-3fc17.firebaseapp.com',
    storageBucket: 'pokedex-3fc17.firebasestorage.app',
    measurementId: 'G-X6K7EPT14K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMik9TxidsAc_aXRDO2yhEnEn68DBgIVI',
    appId: '1:279667373401:android:d0b15b95ae52cb6efbc848',
    messagingSenderId: '279667373401',
    projectId: 'pokedex-3fc17',
    storageBucket: 'pokedex-3fc17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe9fyXhp-MHPtuMvUL-wK4RnLdUf6bI2k',
    appId: '1:279667373401:ios:0bc078f5bcb91793fbc848',
    messagingSenderId: '279667373401',
    projectId: 'pokedex-3fc17',
    storageBucket: 'pokedex-3fc17.firebasestorage.app',
    iosBundleId: 'com.example.pokedexAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe9fyXhp-MHPtuMvUL-wK4RnLdUf6bI2k',
    appId: '1:279667373401:ios:0bc078f5bcb91793fbc848',
    messagingSenderId: '279667373401',
    projectId: 'pokedex-3fc17',
    storageBucket: 'pokedex-3fc17.firebasestorage.app',
    iosBundleId: 'com.example.pokedexAssessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCORQn3b4HRiBLSgRMrbIgGMq4saEG8Nso',
    appId: '1:279667373401:web:621372b3cf4f8b91fbc848',
    messagingSenderId: '279667373401',
    projectId: 'pokedex-3fc17',
    authDomain: 'pokedex-3fc17.firebaseapp.com',
    storageBucket: 'pokedex-3fc17.firebasestorage.app',
    measurementId: 'G-3RTGLPMW85',
  );
}
